version: '3'

services:
  redis:
    image: redis:latest
    healthcheck:
      test: "redis-cli monitor"

  app:
    build:
      context: .
    ports:
      - "8001:8001"
    depends_on:
      - redis
    links:
      - redis