// Code generated by protoc-gen-go. DO NOT EDIT.
// source: connection.proto

package connection_grpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthResponse_ResultMessage int32

const (
	AuthResponse_MESSAGE_FAILED  AuthResponse_ResultMessage = 0
	AuthResponse_MESSAGE_SUCCESS AuthResponse_ResultMessage = 1
)

var AuthResponse_ResultMessage_name = map[int32]string{
	0: "MESSAGE_FAILED",
	1: "MESSAGE_SUCCESS",
}

var AuthResponse_ResultMessage_value = map[string]int32{
	"MESSAGE_FAILED":  0,
	"MESSAGE_SUCCESS": 1,
}

func (x AuthResponse_ResultMessage) String() string {
	return proto.EnumName(AuthResponse_ResultMessage_name, int32(x))
}

func (AuthResponse_ResultMessage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{3, 0}
}

type AuthDeviceInfo_DeviceType int32

const (
	AuthDeviceInfo_DEVICE_TABLET AuthDeviceInfo_DeviceType = 0
	AuthDeviceInfo_DEVICE_WEB    AuthDeviceInfo_DeviceType = 1
)

var AuthDeviceInfo_DeviceType_name = map[int32]string{
	0: "DEVICE_TABLET",
	1: "DEVICE_WEB",
}

var AuthDeviceInfo_DeviceType_value = map[string]int32{
	"DEVICE_TABLET": 0,
	"DEVICE_WEB":    1,
}

func (x AuthDeviceInfo_DeviceType) String() string {
	return proto.EnumName(AuthDeviceInfo_DeviceType_name, int32(x))
}

func (AuthDeviceInfo_DeviceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{6, 0}
}

type ConnectionRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionRequest) Reset()         { *m = ConnectionRequest{} }
func (m *ConnectionRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectionRequest) ProtoMessage()    {}
func (*ConnectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{0}
}

func (m *ConnectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionRequest.Unmarshal(m, b)
}
func (m *ConnectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionRequest.Marshal(b, m, deterministic)
}
func (m *ConnectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionRequest.Merge(m, src)
}
func (m *ConnectionRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectionRequest.Size(m)
}
func (m *ConnectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionRequest proto.InternalMessageInfo

func (m *ConnectionRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ConnectionResponse struct {
	ConnectionCode       string   `protobuf:"bytes,1,opt,name=connectionCode,proto3" json:"connectionCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectionResponse) Reset()         { *m = ConnectionResponse{} }
func (m *ConnectionResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectionResponse) ProtoMessage()    {}
func (*ConnectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{1}
}

func (m *ConnectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectionResponse.Unmarshal(m, b)
}
func (m *ConnectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectionResponse.Marshal(b, m, deterministic)
}
func (m *ConnectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectionResponse.Merge(m, src)
}
func (m *ConnectionResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectionResponse.Size(m)
}
func (m *ConnectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectionResponse proto.InternalMessageInfo

func (m *ConnectionResponse) GetConnectionCode() string {
	if m != nil {
		return m.ConnectionCode
	}
	return ""
}

type AuthRequest struct {
	ConnectionCode       string          `protobuf:"bytes,1,opt,name=connectionCode,proto3" json:"connectionCode,omitempty"`
	DeviceInfo           *AuthDeviceInfo `protobuf:"bytes,2,opt,name=deviceInfo,proto3" json:"deviceInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{2}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetConnectionCode() string {
	if m != nil {
		return m.ConnectionCode
	}
	return ""
}

func (m *AuthRequest) GetDeviceInfo() *AuthDeviceInfo {
	if m != nil {
		return m.DeviceInfo
	}
	return nil
}

type AuthResponse struct {
	Message              AuthResponse_ResultMessage `protobuf:"varint,1,opt,name=message,proto3,enum=connection_grpc.AuthResponse_ResultMessage" json:"message,omitempty"`
	UserId               string                     `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *AuthResponse) Reset()         { *m = AuthResponse{} }
func (m *AuthResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()    {}
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{3}
}

func (m *AuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResponse.Unmarshal(m, b)
}
func (m *AuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResponse.Marshal(b, m, deterministic)
}
func (m *AuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResponse.Merge(m, src)
}
func (m *AuthResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResponse.Size(m)
}
func (m *AuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResponse proto.InternalMessageInfo

func (m *AuthResponse) GetMessage() AuthResponse_ResultMessage {
	if m != nil {
		return m.Message
	}
	return AuthResponse_MESSAGE_FAILED
}

func (m *AuthResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type WaitAuthRequest struct {
	UserId               string          `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	AuthDevice           *AuthDeviceInfo `protobuf:"bytes,2,opt,name=authDevice,proto3" json:"authDevice,omitempty"`
	AcceptDevice         bool            `protobuf:"varint,3,opt,name=acceptDevice,proto3" json:"acceptDevice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WaitAuthRequest) Reset()         { *m = WaitAuthRequest{} }
func (m *WaitAuthRequest) String() string { return proto.CompactTextString(m) }
func (*WaitAuthRequest) ProtoMessage()    {}
func (*WaitAuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{4}
}

func (m *WaitAuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitAuthRequest.Unmarshal(m, b)
}
func (m *WaitAuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitAuthRequest.Marshal(b, m, deterministic)
}
func (m *WaitAuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitAuthRequest.Merge(m, src)
}
func (m *WaitAuthRequest) XXX_Size() int {
	return xxx_messageInfo_WaitAuthRequest.Size(m)
}
func (m *WaitAuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitAuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WaitAuthRequest proto.InternalMessageInfo

func (m *WaitAuthRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *WaitAuthRequest) GetAuthDevice() *AuthDeviceInfo {
	if m != nil {
		return m.AuthDevice
	}
	return nil
}

func (m *WaitAuthRequest) GetAcceptDevice() bool {
	if m != nil {
		return m.AcceptDevice
	}
	return false
}

type WaitAuthResponse struct {
	AuthDevice           *AuthDeviceInfo `protobuf:"bytes,1,opt,name=authDevice,proto3" json:"authDevice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WaitAuthResponse) Reset()         { *m = WaitAuthResponse{} }
func (m *WaitAuthResponse) String() string { return proto.CompactTextString(m) }
func (*WaitAuthResponse) ProtoMessage()    {}
func (*WaitAuthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{5}
}

func (m *WaitAuthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitAuthResponse.Unmarshal(m, b)
}
func (m *WaitAuthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitAuthResponse.Marshal(b, m, deterministic)
}
func (m *WaitAuthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitAuthResponse.Merge(m, src)
}
func (m *WaitAuthResponse) XXX_Size() int {
	return xxx_messageInfo_WaitAuthResponse.Size(m)
}
func (m *WaitAuthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitAuthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_WaitAuthResponse proto.InternalMessageInfo

func (m *WaitAuthResponse) GetAuthDevice() *AuthDeviceInfo {
	if m != nil {
		return m.AuthDevice
	}
	return nil
}

type AuthDeviceInfo struct {
	DeviceType           AuthDeviceInfo_DeviceType `protobuf:"varint,1,opt,name=deviceType,proto3,enum=connection_grpc.AuthDeviceInfo_DeviceType" json:"deviceType,omitempty"`
	DeviceName           string                    `protobuf:"bytes,2,opt,name=deviceName,proto3" json:"deviceName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *AuthDeviceInfo) Reset()         { *m = AuthDeviceInfo{} }
func (m *AuthDeviceInfo) String() string { return proto.CompactTextString(m) }
func (*AuthDeviceInfo) ProtoMessage()    {}
func (*AuthDeviceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{6}
}

func (m *AuthDeviceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthDeviceInfo.Unmarshal(m, b)
}
func (m *AuthDeviceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthDeviceInfo.Marshal(b, m, deterministic)
}
func (m *AuthDeviceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthDeviceInfo.Merge(m, src)
}
func (m *AuthDeviceInfo) XXX_Size() int {
	return xxx_messageInfo_AuthDeviceInfo.Size(m)
}
func (m *AuthDeviceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthDeviceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AuthDeviceInfo proto.InternalMessageInfo

func (m *AuthDeviceInfo) GetDeviceType() AuthDeviceInfo_DeviceType {
	if m != nil {
		return m.DeviceType
	}
	return AuthDeviceInfo_DEVICE_TABLET
}

func (m *AuthDeviceInfo) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_51baa40a1cc6b48b, []int{7}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("connection_grpc.AuthResponse_ResultMessage", AuthResponse_ResultMessage_name, AuthResponse_ResultMessage_value)
	proto.RegisterEnum("connection_grpc.AuthDeviceInfo_DeviceType", AuthDeviceInfo_DeviceType_name, AuthDeviceInfo_DeviceType_value)
	proto.RegisterType((*ConnectionRequest)(nil), "connection_grpc.ConnectionRequest")
	proto.RegisterType((*ConnectionResponse)(nil), "connection_grpc.ConnectionResponse")
	proto.RegisterType((*AuthRequest)(nil), "connection_grpc.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "connection_grpc.AuthResponse")
	proto.RegisterType((*WaitAuthRequest)(nil), "connection_grpc.WaitAuthRequest")
	proto.RegisterType((*WaitAuthResponse)(nil), "connection_grpc.WaitAuthResponse")
	proto.RegisterType((*AuthDeviceInfo)(nil), "connection_grpc.AuthDeviceInfo")
	proto.RegisterType((*Empty)(nil), "connection_grpc.Empty")
}

func init() { proto.RegisterFile("connection.proto", fileDescriptor_51baa40a1cc6b48b) }

var fileDescriptor_51baa40a1cc6b48b = []byte{
	// 446 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xed, 0x06, 0x68, 0xcb, 0xb4, 0x75, 0xdc, 0x41, 0x42, 0x55, 0xc5, 0x87, 0x59, 0x24, 0x64,
	0x51, 0xc9, 0xa0, 0x70, 0xe1, 0x80, 0x84, 0x5c, 0x7b, 0x41, 0x46, 0x2d, 0x07, 0x6f, 0x4a, 0x8f,
	0x91, 0x71, 0x96, 0x12, 0x89, 0xd8, 0xc6, 0x5e, 0x57, 0xea, 0x9d, 0x33, 0x7f, 0x83, 0x13, 0xff,
	0x11, 0x25, 0xde, 0xf5, 0x47, 0x42, 0x42, 0x38, 0xe6, 0xe5, 0xbd, 0x37, 0x33, 0x6f, 0x66, 0x0d,
	0x66, 0x9c, 0x26, 0x89, 0x88, 0xe5, 0x24, 0x4d, 0x9c, 0x2c, 0x4f, 0x65, 0x8a, 0xfd, 0x06, 0x19,
	0x5d, 0xe5, 0x59, 0x4c, 0x4f, 0xe0, 0xd0, 0xab, 0xa1, 0x50, 0x7c, 0x2f, 0x45, 0x21, 0xf1, 0x3e,
	0x6c, 0x97, 0x85, 0xc8, 0x83, 0xf1, 0x11, 0xb1, 0x88, 0x7d, 0x37, 0x54, 0xbf, 0xe8, 0x1b, 0xc0,
	0x36, 0xb9, 0xc8, 0xd2, 0xa4, 0x10, 0xf8, 0x0c, 0x8c, 0xc6, 0xd5, 0x4b, 0xc7, 0x42, 0xa9, 0x16,
	0x50, 0x7a, 0x0d, 0x7b, 0x6e, 0x29, 0xbf, 0xea, 0x22, 0x1b, 0xca, 0xf0, 0x2d, 0xc0, 0x58, 0x5c,
	0x4f, 0x62, 0x11, 0x24, 0x5f, 0xd2, 0xa3, 0x9e, 0x45, 0xec, 0xbd, 0xc1, 0x63, 0x67, 0x61, 0x0e,
	0x67, 0xe6, 0xec, 0xd7, 0xb4, 0xb0, 0x25, 0xa1, 0xbf, 0x08, 0xec, 0x57, 0x85, 0x55, 0xc3, 0x0c,
	0x76, 0xa6, 0xa2, 0x28, 0xa2, 0xab, 0xaa, 0xa4, 0x31, 0x38, 0xf9, 0xab, 0x9d, 0xe6, 0x3b, 0xa1,
	0x28, 0xca, 0x6f, 0xf2, 0xbc, 0x92, 0x84, 0x5a, 0xdb, 0x4a, 0xa9, 0xd7, 0x49, 0xe9, 0x35, 0x1c,
	0x74, 0x14, 0x88, 0x60, 0x9c, 0x33, 0xce, 0xdd, 0xf7, 0x6c, 0xf4, 0xce, 0x0d, 0xce, 0x98, 0x6f,
	0x6e, 0xe1, 0x3d, 0xe8, 0x6b, 0x8c, 0x5f, 0x78, 0x1e, 0xe3, 0xdc, 0x24, 0xf4, 0x27, 0x81, 0xfe,
	0x65, 0x34, 0x91, 0xed, 0x98, 0x56, 0xec, 0x62, 0x16, 0x4b, 0x54, 0xcf, 0xbc, 0x71, 0x2c, 0x8d,
	0x04, 0x29, 0xec, 0x47, 0x71, 0x2c, 0x32, 0xa9, 0x2c, 0x6e, 0x59, 0xc4, 0xde, 0x0d, 0x3b, 0x18,
	0xe5, 0x60, 0x36, 0xfd, 0xa8, 0xf4, 0xba, 0x85, 0xc9, 0x7f, 0x17, 0xa6, 0xbf, 0x09, 0x18, 0xdd,
	0xbf, 0xf1, 0x83, 0xde, 0xf1, 0xf0, 0x26, 0xd3, 0x4b, 0x79, 0xfe, 0x0f, 0x4f, 0xc7, 0xaf, 0x15,
	0x61, 0x4b, 0x8d, 0x8f, 0xb4, 0xd7, 0xc7, 0x68, 0x2a, 0xd4, 0x6a, 0x5a, 0x08, 0x7d, 0x01, 0xd0,
	0x28, 0xf1, 0x10, 0x0e, 0x7c, 0xf6, 0x29, 0xf0, 0xd8, 0x68, 0xe8, 0x9e, 0x9e, 0xb1, 0xa1, 0xb9,
	0x85, 0x06, 0x80, 0x82, 0x2e, 0xd9, 0xa9, 0x49, 0xe8, 0x0e, 0xdc, 0x61, 0xd3, 0x4c, 0xde, 0x0c,
	0x7e, 0xf4, 0xda, 0x8f, 0x85, 0x8b, 0x7c, 0x9e, 0xe3, 0x05, 0x40, 0x03, 0x22, 0x5d, 0xea, 0x7a,
	0xe9, 0x79, 0x1d, 0x3f, 0x5d, 0xcb, 0x51, 0x31, 0x7b, 0x70, 0x7b, 0x36, 0x2f, 0x3e, 0x58, 0x71,
	0x9b, 0x95, 0xd5, 0xc3, 0xb5, 0x97, 0x8b, 0x1c, 0x76, 0xf5, 0xfe, 0xd0, 0x5a, 0xa2, 0x2e, 0x9c,
	0xda, 0xf1, 0x93, 0x35, 0x8c, 0xca, 0xd0, 0x26, 0x2f, 0xc9, 0xe7, 0xed, 0xf9, 0xa7, 0xe4, 0xd5,
	0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x41, 0x75, 0x91, 0x5e, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ConnectionServiceClient is the client API for ConnectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ConnectionServiceClient interface {
	Connection(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionResponse, error)
	Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	WaitAuth(ctx context.Context, opts ...grpc.CallOption) (ConnectionService_WaitAuthClient, error)
}

type connectionServiceClient struct {
	cc *grpc.ClientConn
}

func NewConnectionServiceClient(cc *grpc.ClientConn) ConnectionServiceClient {
	return &connectionServiceClient{cc}
}

func (c *connectionServiceClient) Connection(ctx context.Context, in *ConnectionRequest, opts ...grpc.CallOption) (*ConnectionResponse, error) {
	out := new(ConnectionResponse)
	err := c.cc.Invoke(ctx, "/connection_grpc.ConnectionService/Connection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) Auth(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/connection_grpc.ConnectionService/Auth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectionServiceClient) WaitAuth(ctx context.Context, opts ...grpc.CallOption) (ConnectionService_WaitAuthClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ConnectionService_serviceDesc.Streams[0], "/connection_grpc.ConnectionService/WaitAuth", opts...)
	if err != nil {
		return nil, err
	}
	x := &connectionServiceWaitAuthClient{stream}
	return x, nil
}

type ConnectionService_WaitAuthClient interface {
	Send(*WaitAuthRequest) error
	Recv() (*WaitAuthResponse, error)
	grpc.ClientStream
}

type connectionServiceWaitAuthClient struct {
	grpc.ClientStream
}

func (x *connectionServiceWaitAuthClient) Send(m *WaitAuthRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *connectionServiceWaitAuthClient) Recv() (*WaitAuthResponse, error) {
	m := new(WaitAuthResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ConnectionServiceServer is the server API for ConnectionService service.
type ConnectionServiceServer interface {
	Connection(context.Context, *ConnectionRequest) (*ConnectionResponse, error)
	Auth(context.Context, *AuthRequest) (*AuthResponse, error)
	WaitAuth(ConnectionService_WaitAuthServer) error
}

func RegisterConnectionServiceServer(s *grpc.Server, srv ConnectionServiceServer) {
	s.RegisterService(&_ConnectionService_serviceDesc, srv)
}

func _ConnectionService_Connection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).Connection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connection_grpc.ConnectionService/Connection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).Connection(ctx, req.(*ConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectionServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/connection_grpc.ConnectionService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectionServiceServer).Auth(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectionService_WaitAuth_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConnectionServiceServer).WaitAuth(&connectionServiceWaitAuthServer{stream})
}

type ConnectionService_WaitAuthServer interface {
	Send(*WaitAuthResponse) error
	Recv() (*WaitAuthRequest, error)
	grpc.ServerStream
}

type connectionServiceWaitAuthServer struct {
	grpc.ServerStream
}

func (x *connectionServiceWaitAuthServer) Send(m *WaitAuthResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *connectionServiceWaitAuthServer) Recv() (*WaitAuthRequest, error) {
	m := new(WaitAuthRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ConnectionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "connection_grpc.ConnectionService",
	HandlerType: (*ConnectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Connection",
			Handler:    _ConnectionService_Connection_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _ConnectionService_Auth_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WaitAuth",
			Handler:       _ConnectionService_WaitAuth_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "connection.proto",
}
